version: "3.3"
name: sausage-store
services:

  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-012-042/sausage-store/sausage-backend-report:latest
    container_name: sausage-store-backend-report
    environment:
      DB: ${DB}
      PORT: 8080
    networks:
      - sausage-store

  frontend:
    image: gitlab.praktikum-services.ru:5050/std-012-042/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    environment:
      DEFAULT_HOST: myproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    networks:
      - sausage-store

  backend-blue:
    image: gitlab.praktikum-services.ru:5050/std-012-042/sausage-store/sausage-backend:latest
    restart: always
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${SPRING_CLOUD_VAULT_TOKEN}
      REPORT_PATH: /app/reports
      VIRTUAL_HOST: myproxy
    networks:
      - sausage-store
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

  backend-green:
    image: gitlab.praktikum-services.ru:5050/std-012-042/sausage-store/sausage-backend:latest
    restart: always
    environment:
      SPRING_CLOUD_VAULT_TOKEN: ${SPRING_CLOUD_VAULT_TOKEN}
      REPORT_PATH: /app/reports
      VIRTUAL_HOST: myproxy
    networks:
      - sausage-store
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s

networks:
  sausage-store:
    name: sausage-store